In [1]:
import numpy as np
import matplotlib.pyplot as plt
from particle_filtering import particle_filtering_func, discrete_cem_func, continuous_cem_func
from setup import setup_class
import torch


In [2]:
# Problem setup
# prob = "CartPole"
prob = "Acrobot"
# prob = "MountainCar"
# prob = "LunarLander"
# prob = "Pendulum"
# prob = "Pendulum_xyomega"
# prob = "MountainCarContinuous"
# prob = "LunarLanderContinuous"
# prob = "PandaReacher"
# prob = "PandaPusher"
# prob = "MuJoCoReacher"
# prob = "MuJoCoPusher"

print("prob ", prob, "\n")


prob_vars = setup_class(prob)


prob  Acrobot 



Test PF


In [3]:
if prob_vars.prob == "CartPole":
    particles = np.random.randint(0, 2, (prob_vars.num_particles, prob_vars.horizon))
elif prob_vars.prob == "Acrobot" or prob_vars.prob == "MountainCar":
    particles = np.random.randint(0, 3, (prob_vars.num_particles, prob_vars.horizon))
elif prob_vars.prob == "LunarLander":
    particles = np.random.randint(0, 4, (prob_vars.num_particles, prob_vars.horizon))
elif prob_vars.prob == "PandaReacher" or prob_vars.prob == "MuJoCoReacher" or prob_vars.prob == "PandaPusher" or prob_vars.prob == "MuJoCoPusher" or prob_vars.prob == "LunarLanderContinuous":
    particles = np.random.uniform(prob_vars.action_low, prob_vars.action_high, (prob_vars.num_particles, prob_vars.action_dim*prob_vars.horizon))
else: # Pendulum, MountainCarContinuous
    particles = np.random.uniform(prob_vars.action_low, prob_vars.action_high, (prob_vars.num_particles, prob_vars.horizon))

# num_particles = 30
print("prob_vars.horizon ", prob_vars.horizon, "\n")

# if prob_vars.prob == "CartPole":
#     particles = np.random.randint(0, 2, (num_particles, prob_vars.horizon))
# elif prob_vars.prob == "Acrobot" or prob_vars.prob == "MountainCar":
#     particles = np.random.randint(0, 3, (num_particles, prob_vars.horizon))
# elif prob_vars.prob == "LunarLander":
#     particles = np.random.randint(0, 4, (num_particles, prob_vars.horizon))
# elif prob_vars.prob == "PandaReacher" or prob_vars.prob == "MuJoCoReacher" or prob_vars.prob == "PandaPusher" or prob_vars.prob == "MuJoCoPusher" or prob_vars.prob == "LunarLanderContinuous":
#     particles = np.random.uniform(prob_vars.action_low, prob_vars.action_high, (num_particles, prob_vars.action_dim*prob_vars.horizon))
# else: # Pendulum, MountainCarContinuous
#     particles = np.random.uniform(prob_vars.action_low, prob_vars.action_high, (num_particles, prob_vars.horizon))

# print("particles ", particles, "\n")
print("particles shape ", particles.shape, "\n")

costs = torch.zeros(prob_vars.num_particles)
# costs = torch.zeros((num_particles, prob_vars.horizon))
best_action_sequence = particles[0]

best_first_action, actions = particle_filtering_func(prob_vars, particles, costs, best_action_sequence)


print("actions ", actions, "\n")
print("best_first_action ", best_first_action, "\n")
print("actions shape ", actions.shape, "\n")



prob_vars.horizon  30 

particles shape  (100, 30) 

actions  [[1 1 0 ... 1 0 2]
 [0 1 2 ... 1 2 0]
 [1 1 0 ... 1 0 2]
 ...
 [2 0 0 ... 2 1 0]
 [2 2 2 ... 1 0 1]
 [0 0 1 ... 1 2 2]] 

best_first_action  1 

actions shape  (100, 30) 



Test CEM 


In [4]:
if prob_vars.prob == "CartPole":
    particles = np.random.randint(0, 2, (prob_vars.num_particles, prob_vars.horizon))
elif prob_vars.prob == "Acrobot" or prob_vars.prob == "MountainCar":
    particles = np.random.randint(0, 3, (prob_vars.num_particles, prob_vars.horizon))
elif prob_vars.prob == "LunarLander":
    particles = np.random.randint(0, 4, (prob_vars.num_particles, prob_vars.horizon))
elif prob_vars.prob == "PandaReacher" or prob_vars.prob == "MuJoCoReacher" or prob_vars.prob == "PandaPusher" or prob_vars.prob == "MuJoCoPusher" or prob_vars.prob == "LunarLanderContinuous":
    particles = np.random.uniform(prob_vars.action_low, prob_vars.action_high, (prob_vars.num_particles, prob_vars.action_dim*prob_vars.horizon))
else: # Pendulum, MountainCarContinuous
    particles = np.random.uniform(prob_vars.action_low, prob_vars.action_high, (prob_vars.num_particles, prob_vars.horizon))

# num_particles = 30
print("prob_vars.horizon ", prob_vars.horizon, "\n")

# if prob_vars.prob == "CartPole":
#     particles = np.random.randint(0, 2, (num_particles, prob_vars.horizon))
# elif prob_vars.prob == "Acrobot" or prob_vars.prob == "MountainCar":
#     particles = np.random.randint(0, 3, (num_particles, prob_vars.horizon))
# elif prob_vars.prob == "LunarLander":
#     particles = np.random.randint(0, 4, (num_particles, prob_vars.horizon))
# elif prob_vars.prob == "PandaReacher" or prob_vars.prob == "MuJoCoReacher" or prob_vars.prob == "PandaPusher" or prob_vars.prob == "MuJoCoPusher" or prob_vars.prob == "LunarLanderContinuous":
#     particles = np.random.uniform(prob_vars.action_low, prob_vars.action_high, (num_particles, prob_vars.action_dim*prob_vars.horizon))
# else: # Pendulum, MountainCarContinuous
#     particles = np.random.uniform(prob_vars.action_low, prob_vars.action_high, (num_particles, prob_vars.horizon))

# print("particles ", particles, "\n")
print("particles shape ", particles.shape, "\n")

costs = torch.zeros(prob_vars.num_particles)
# costs = torch.zeros((num_particles, prob_vars.horizon))
best_action_sequence = particles[0]

if prob_vars.discrete:
    best_first_action, actions = discrete_cem_func(prob_vars, particles, costs, best_action_sequence)

else:
    best_first_action, actions = continuous_cem_func(prob_vars, particles, costs, best_action_sequence)


print("actions ", actions, "\n")
print("actions shape ", actions.shape, "\n")



prob_vars.horizon  30 

particles shape  (100, 30) 

actions  [[2 1 1 ... 0 1 0]
 [0 1 1 ... 0 1 0]
 [1 0 1 ... 1 0 0]
 ...
 [2 0 2 ... 0 0 0]
 [2 2 0 ... 1 2 1]
 [0 2 1 ... 0 1 0]] 

actions shape  (100, 30) 

