In [1]:
import numpy as np
import gymnasium as gym
import torch
import copy
import panda_gym


In [3]:
seed = 15


# Environments that work



## Cart Pole (discrete)


In [50]:
env = gym.make('CartPole-v1').unwrapped # .unwrapped is used to access the state directly
env.reset(seed=seed)


(array([ 0.01927434,  0.03158171, -0.01555932, -0.04551618], dtype=float32),
 {})

In [56]:
horizon = 2
num_particles = 5

sim_states = env.state

for h in range(horizon):
    print("h =", h, "\n")
    next_states = []
    for i in range(num_particles):
        print("i ", i, "\n")
        if h >0:
            env_i = copy.deepcopy(env)  # Assuming prob_vars.env is an environment object with a copy method
            env_i.reset(seed=seed)
            env_i.state = sim_states[i].numpy()  # Set the initial state of the environment
        else: # if h == 0:
            env_i = copy.deepcopy(env)  # Assuming prob_vars.env is an environment object with a copy method
            env_i.reset(seed=seed)
            if isinstance(sim_states, torch.Tensor):
                sim_states.detach().cpu().numpy()  # Safely convert to NumPy
            env_i.state = sim_states # Set the initial state of the environment
        print("env_i.state ", env_i.state, "\n")
        # print(env_i.step(env_i.action_space.sample()))
        action = env_i.action_space.sample()
        next_state_step, reward, terminated, truncated, info = env_i.step(action)  # Sample a random action
        next_state = env_i.state
        print("next_state ", next_state, "\n")
        next_states.append(next_state)
    
    next_states = np.clip(next_states, env.observation_space.low, env.observation_space.high)
    sim_states = torch.tensor(next_states, dtype=torch.float32)
    print("sim_states", sim_states, "\n")
    # sim_states = torch.clip(sim_states, env.observation_space.low, env.observation_space.high)
    


h = 0 

i  0 

env_i.state  [ 0.01927434  0.03158171 -0.01555932 -0.04551618] 

next_state  (0.019905971019187348, -0.08655294196659766, -0.016469647869333498, 0.1270900912606458) 

i  1 

env_i.state  [ 0.01927434  0.03158171 -0.01555932 -0.04551618] 

next_state  (0.019905971019187348, 0.0014594708235263036, -0.016469647869333498, -0.004912547883514723) 

i  2 

env_i.state  [ 0.01927434  0.03158171 -0.01555932 -0.04551618] 

next_state  (0.019905971019187348, -0.15515744052636463, -0.016469647869333498, 0.22998438287205802) 

i  3 

env_i.state  [ 0.01927434  0.03158171 -0.01555932 -0.04551618] 

next_state  (0.019905971019187348, -0.06759462778457094, -0.016469647869333498, 0.09865606216841635) 

i  4 

env_i.state  [ 0.01927434  0.03158171 -0.01555932 -0.04551618] 

next_state  (0.019905971019187348, -0.09673757295243982, -0.016469647869333498, 0.1423651885590966) 

sim_states tensor([[ 0.0199, -0.0866, -0.0165,  0.1271],
        [ 0.0199,  0.0015, -0.0165, -0.0049],
        [ 0.0

## Cart Pole (continuous)


In [52]:
import cartpole_continuous as cartpole_env
            
env = cartpole_env.CartPoleContinuousEnv(render_mode="rgb_array").unwrapped # .unwrapped is used to access the state directly
env.reset(seed=seed)


(array([ 0.01927434,  0.03158171, -0.01555932, -0.04551618]), {})

In [57]:
horizon = 2
num_particles = 5

sim_states = env.state

for h in range(horizon):
    print("h =", h, "\n")
    next_states = []
    for i in range(num_particles):
        print("i ", i, "\n")
        if h >0:
            env_i = copy.deepcopy(env)  # Assuming prob_vars.env is an environment object with a copy method
            env_i.reset(seed=seed)
            env_i.state = sim_states[i].numpy()  # Set the initial state of the environment
        else: # if h == 0:
            env_i = copy.deepcopy(env)  # Assuming prob_vars.env is an environment object with a copy method
            env_i.reset(seed=seed)
            if isinstance(sim_states, torch.Tensor):
                sim_states.detach().cpu().numpy()  # Safely convert to NumPy
            env_i.state = sim_states # Set the initial state of the environment
        print("env_i.state ", env_i.state, "\n")
        # print(env_i.step(env_i.action_space.sample()))
        action = env_i.action_space.sample()
        next_state_step, reward, terminated, truncated, info = env_i.step(action)  # Sample a random action
        next_state = env_i.state
        print("action ", action, "\n")
        print("next_state ", next_state, "\n")
        next_states.append(next_state)
    
    next_states = np.clip(next_states, env.observation_space.low, env.observation_space.high)
    sim_states = torch.tensor(next_states, dtype=torch.float32)
    print("sim_states", sim_states, "\n")
    # sim_states = torch.clip(sim_states, env.observation_space.low, env.observation_space.high)
    


h = 0 

i  0 

env_i.state  [ 0.01927434  0.03158171 -0.01555932 -0.04551618] 

action  [-0.01280423] 

next_state  (0.019905971019187348, 0.029306441707807725, -0.016469647869333498, -0.046677948153375545) 

i  1 

env_i.state  [ 0.01927434  0.03158171 -0.01555932 -0.04551618] 

action  [-0.96558434] 

next_state  (0.019905971019187348, -0.15659857971448876, -0.016469647869333498, 0.23214582999270555) 

i  2 

env_i.state  [ 0.01927434  0.03158171 -0.01555932 -0.04551618] 

action  [0.77778393] 

next_state  (0.019905971019187348, 0.18356481323550308, -0.016469647869333498, -0.27803749740574113) 

i  3 

env_i.state  [ 0.01927434  0.03158171 -0.01555932 -0.04551618] 

action  [-0.10685021] 

next_state  (0.019905971019187348, 0.01095633163422978, -0.016469647869333498, -0.01915611479477523) 

i  4 

env_i.state  [ 0.01927434  0.03158171 -0.01555932 -0.04551618] 

action  [0.8319744] 

next_state  (0.019905971019187348, 0.1941383736310199, -0.016469647869333498, -0.2938959182024383) 



## Mountain Car (discrete)


In [58]:
env = gym.make("MountainCar", render_mode="rgb_array").unwrapped # .unwrapped is used to access the state directly
env.reset(seed=seed)


c:\Users\nicle\anaconda3\Lib\site-packages\gymnasium\envs\registration.py:525: UserWarning: WARN: Using the latest versioned environment `MountainCar-v0` instead of the unversioned environment `MountainCar`.
  logger.warn(


(array([-0.46145132,  0.        ], dtype=float32), {})

In [61]:
horizon = 2
num_particles = 5

sim_states = env.state

for h in range(horizon):
    print("h =", h, "\n")
    next_states = []
    for i in range(num_particles):
        print("i ", i, "\n")
        if h >0:
            env_i = copy.deepcopy(env)  # Assuming prob_vars.env is an environment object with a copy method
            env_i.reset(seed=seed)
            env_i.state = sim_states[i].numpy()  # Set the initial state of the environment
        else: # if h == 0:
            env_i = copy.deepcopy(env)  # Assuming prob_vars.env is an environment object with a copy method
            env_i.reset(seed=seed)
            if isinstance(sim_states, torch.Tensor):
                sim_states.detach().cpu().numpy()  # Safely convert to NumPy
            env_i.state = sim_states # Set the initial state of the environment
        print("env_i.state ", env_i.state, "\n")
        # print(env_i.step(env_i.action_space.sample()))
        action = env_i.action_space.sample()
        next_state_step, reward, terminated, truncated, info = env_i.step(action)  # Sample a random action
        next_state = env_i.state
        print("action ", action, "\n")
        print("next_state ", next_state, "\n")
        next_states.append(next_state)
    
    next_states = np.clip(next_states, env.observation_space.low, env.observation_space.high)
    sim_states = torch.tensor(next_states, dtype=torch.float32)
    print("sim_states", sim_states, "\n")
    # sim_states = torch.clip(sim_states, env.observation_space.low, env.observation_space.high)
    


h = 0 

i  0 

env_i.state  [-0.46145133  0.        ] 

action  1 

next_state  (-0.4619147366005067, -0.0004634101935372057) 

i  1 

env_i.state  [-0.46145133  0.        ] 

action  0 

next_state  (-0.4629147366005067, -0.0014634101935372059) 

i  2 

env_i.state  [-0.46145133  0.        ] 

action  0 

next_state  (-0.4629147366005067, -0.0014634101935372059) 

i  3 

env_i.state  [-0.46145133  0.        ] 

action  0 

next_state  (-0.4629147366005067, -0.0014634101935372059) 

i  4 

env_i.state  [-0.46145133  0.        ] 

action  1 

next_state  (-0.4619147366005067, -0.0004634101935372057) 

sim_states tensor([[-0.4619, -0.0005],
        [-0.4629, -0.0015],
        [-0.4629, -0.0015],
        [-0.4629, -0.0015],
        [-0.4619, -0.0005]]) 

h = 1 

i  0 

env_i.state  [-0.46191475 -0.00046341] 

action  0 

next_state  (-0.4638381524654559, -0.0019234045120409948) 

i  1 

env_i.state  [-0.46291474 -0.00146341] 

action  1 

next_state  (-0.4648307656952789, -0.0019160306164

## Mountain Car (continuous)


In [34]:
env = gym.make("MountainCar", render_mode="rgb_array").unwrapped # .unwrapped is used to access the state directly
env.reset(seed=seed)


(array([-0.46145132,  0.        ], dtype=float32), {})

In [ ]:
horizon = 2
num_particles = 5

sim_states = env.state

for h in range(horizon):
    print("h =", h, "\n")
    next_states = []
    for i in range(num_particles):
        print("i ", i, "\n")
        if h >0:
            env_i = copy.deepcopy(env)  # Assuming prob_vars.env is an environment object with a copy method
            env_i.reset(seed=seed)
            env_i.state = sim_states[i].numpy()  # Set the initial state of the environment
        else: # if h == 0:
            env_i = copy.deepcopy(env)  # Assuming prob_vars.env is an environment object with a copy method
            env_i.reset(seed=seed)
            # if isinstance(sim_states, torch.Tensor):
            #     sim_states.detach().cpu().numpy()  # Safely convert to NumPy
            env_i.state = sim_states # Set the initial state of the environment
        print("env_i.state ", env_i.state, "\n")
        # print(env_i.step(env_i.action_space.sample()))
        action = env_i.action_space.sample()
        next_state_step, reward, terminated, truncated, info = env_i.step(action)  # Sample a random action
        next_state = env_i.state
        print("action ", action, "\n")
        print("next_state ", next_state, "\n")
        next_states.append(next_state)
    
    next_states = np.clip(next_states, env.observation_space.low, env.observation_space.high)
    sim_states = torch.tensor(next_states, dtype=torch.float32)
    print("sim_states", sim_states, "\n")
    # sim_states = torch.clip(sim_states, env.observation_space.low, env.observation_space.high)
    


h = 0 

i  0 

env_i.state  -0.4614513264069695 



TypeError: cannot unpack non-iterable numpy.float64 object

## Panda Reach (dense or sparse rewards)


In [42]:
env = gym.make("PandaReach-v3", render_mode="rgb_array").unwrapped # .unwrapped is used to access the state directly
observation, info = env.reset(seed=seed)
state = observation['observation']
observation, state


({'observation': array([ 3.8439669e-02, -2.1944723e-12,  1.9740014e-01,  0.0000000e+00,
         -0.0000000e+00,  0.0000000e+00], dtype=float32),
  'achieved_goal': array([ 3.8439669e-02, -2.1944723e-12,  1.9740014e-01], dtype=float32),
  'desired_goal': array([0.05782301, 0.09474514, 0.10332203], dtype=float32)},
 array([ 3.8439669e-02, -2.1944723e-12,  1.9740014e-01,  0.0000000e+00,
        -0.0000000e+00,  0.0000000e+00], dtype=float32))

In [43]:
horizon = 2
num_particles = 5

state_ids = np.array([env.save_state() for _ in range(num_particles)], dtype=object)
state_ids[:] = env.save_state()  # Save the initial state of the environment

for h in range(horizon):
    print("h =", h, "\n")
    next_states = []
    for i in range(num_particles):
        print("i ", i, "\n")
        env.restore_state(state_ids[i])
        env.remove_state(state_ids[i])
        
        action = env.action_space.sample()
        next_state_step, reward, terminated, truncated, info = env.step(action)  # Sample a random action

        state_ids[i] = env.save_state()
            
        next_states.append(next_state_step['observation'])
        
        print("action ", action, "\n")
        print("next_state_step ", next_state_step, "\n")
    
    # next_states = np.clip(next_states, env.observation_space.low, env.observation_space.high)
    # sim_states = torch.tensor(next_states, dtype=torch.float32)
    # print("sim_states", sim_states, "\n")
    # sim_states = torch.clip(sim_states, env.observation_space.low, env.observation_space.high)
    


h = 0 

i  0 

action  [ 0.83247334 -0.89065814 -0.97416496] 

next_state_step  {'observation': array([ 0.07388315, -0.02262967,  0.186062  ,  0.22507364, -1.0759819 ,
       -1.2219623 ], dtype=float32), 'achieved_goal': array([ 0.07388315, -0.02262967,  0.186062  ], dtype=float32), 'desired_goal': array([0.05782301, 0.09474514, 0.10332203], dtype=float32)} 

i  1 

action  [-0.33444116  0.47676137  0.13973841] 

next_state_step  {'observation': array([ 0.04593961, -0.04136471,  0.1352841 , -0.43256766,  0.11031865,
       -0.91326004], dtype=float32), 'achieved_goal': array([ 0.04593961, -0.04136471,  0.1352841 ], dtype=float32), 'desired_goal': array([0.05782301, 0.09474514, 0.10332203], dtype=float32)} 

i  2 

action  [-0.46033     0.22527717 -0.34618923] 

next_state_step  {'observation': array([ 0.03278071, -0.03195858,  0.10610695, -0.1948292 ,  0.09315319,
       -0.36483383], dtype=float32), 'achieved_goal': array([ 0.03278071, -0.03195858,  0.10610695], dtype=float32), 'desi

In [27]:
next_states

[array([-0.08702072, -0.0112063 ,  0.26086777, -0.17163223, -1.211889  ,
         0.5001206 ], dtype=float32),
 array([-0.06001816, -0.02955841,  0.28211418,  0.34303477,  0.37377453,
         0.23396528], dtype=float32),
 array([-0.04143569, -0.04477818,  0.3038964 ,  0.21430662, -1.1719104 ,
         0.5652366 ], dtype=float32),
 array([-0.04942478, -0.0614167 ,  0.32240614, -0.02463246,  0.37749085,
         0.26439935], dtype=float32),
 array([-0.03534625, -0.05761719,  0.33242223,  0.16460375,  0.01213752,
         0.08577067], dtype=float32)]

## Panda Push (dense or sparse rewards)


In [28]:
env = gym.make("PandaPush-v3", render_mode="rgb_array").unwrapped # .unwrapped is used to access the state directly
observation, info = env.reset(seed=seed)
state = observation['observation']
observation, state


({'observation': array([ 3.8439669e-02, -2.1944723e-12,  1.9740014e-01,  0.0000000e+00,
         -0.0000000e+00,  0.0000000e+00, -1.3654855e-01,  2.1479176e-02,
          2.0000000e-02,  0.0000000e+00, -0.0000000e+00,  0.0000000e+00,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
          0.0000000e+00,  0.0000000e+00], dtype=float32),
  'achieved_goal': array([-0.13654855,  0.02147918,  0.02      ], dtype=float32),
  'desired_goal': array([0.05782301, 0.09474514, 0.02      ], dtype=float32)},
 array([ 3.8439669e-02, -2.1944723e-12,  1.9740014e-01,  0.0000000e+00,
        -0.0000000e+00,  0.0000000e+00, -1.3654855e-01,  2.1479176e-02,
         2.0000000e-02,  0.0000000e+00, -0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00], dtype=float32))

In [29]:
horizon = 2
num_particles = 5

state_ids = np.array([env.save_state() for _ in range(num_particles)], dtype=object)
state_ids[:] = env.save_state()  # Save the initial state of the environment

for h in range(horizon):
    print("h =", h, "\n")
    next_states = []
    for i in range(num_particles):
        print("i ", i, "\n")
        env.restore_state(state_ids[i])
        env.remove_state(state_ids[i])
        
        action = env.action_space.sample()
        next_state_step, reward, terminated, truncated, info = env.step(action)  # Sample a random action

        state_ids[i] = env.save_state()
            
        next_states.append(next_state_step['observation'])
        
        print("action ", action, "\n")
        print("next_state_step ", next_state_step, "\n")
    
    # next_states = np.clip(next_states, env.observation_space.low, env.observation_space.high)
    # sim_states = torch.tensor(next_states, dtype=torch.float32)
    # print("sim_states", sim_states, "\n")
    # sim_states = torch.clip(sim_states, env.observation_space.low, env.observation_space.high)
    


h = 0 

i  0 

action  [-0.47496682 -0.61775315  0.49273023] 

next_state_step  {'observation': array([ 1.95859764e-02, -2.13152785e-02,  2.01412484e-01, -8.85352120e-02,
       -5.51360190e-01,  5.36332071e-01, -1.36549190e-01,  2.14795396e-02,
        1.99895296e-02,  4.48686751e-06, -3.08392118e-05, -3.87872387e-06,
       -5.73867237e-06,  1.09538505e-05, -5.08076300e-06,  5.10964995e-08,
       -2.53998151e-04, -9.67000524e-05], dtype=float32), 'achieved_goal': array([-0.13654919,  0.02147954,  0.01998953], dtype=float32), 'desired_goal': array([0.05782301, 0.09474514, 0.02      ], dtype=float32)} 

i  1 

action  [ 0.5809905   0.3511775  -0.58508754] 

next_state_step  {'observation': array([ 4.60014157e-02, -1.95030067e-02,  2.07699180e-01,  1.23327814e-01,
        7.04958379e-01, -7.59111941e-01, -1.36549309e-01,  2.14799773e-02,
        1.99894346e-02,  4.48783976e-06, -3.55768534e-05, -7.74457658e-06,
       -1.61770095e-06,  1.09538014e-05, -9.57692350e-07,  9.50089607e-09,


In [30]:
next_states

[array([ 1.50694400e-02,  1.84906311e-02,  1.57929957e-01, -1.64167911e-01,
         2.58065403e-01, -1.51656538e-01, -1.36549443e-01,  2.14817300e-02,
         1.99894123e-02,  4.48807577e-06, -3.66759341e-05, -2.32015627e-05,
        -6.61656088e-07,  1.09536695e-05, -1.21293620e-09,  7.81060078e-11,
        -6.06878885e-08, -9.66072184e-05], dtype=float32),
 array([ 2.43929233e-02,  5.40852034e-03,  1.63751885e-01,  2.84194618e-01,
        -9.03673768e-01,  4.33565378e-01, -1.36549473e-01,  2.14821678e-02,
         1.99894123e-02,  4.48807850e-06, -3.66770691e-05, -2.70658911e-05,
        -6.60658259e-07,  1.09536395e-05, -2.31872244e-10,  6.92109425e-11,
        -1.16441239e-08, -9.66091247e-05], dtype=float32),
 array([ 3.96632589e-02, -6.10010605e-03,  1.93619251e-01,  2.83251286e-01,
         3.20531070e-01,  6.13720536e-01, -1.36549488e-01,  2.14826055e-02,
         1.99894123e-02,  4.48808123e-06, -3.66772947e-05, -3.09302959e-05,
        -6.60456124e-07,  1.09536095e-05, -4.6

# Environments that don't work



## Pendulum

Clipping the next state is problematic since the step gives a 3D state and the env.state givees a 2D state. This isn't
too problematic since the MPC methods seem to work well on this env.


In [64]:
env = gym.make("Pendulum", render_mode="rgb_array").unwrapped # .unwrapped is used to access the state directly
env.reset(seed=seed)


c:\Users\nicle\anaconda3\Lib\site-packages\gymnasium\envs\registration.py:525: UserWarning: WARN: Using the latest versioned environment `Pendulum-v1` instead of the unversioned environment `Pendulum`.
  logger.warn(


(array([0.35204402, 0.9359834 , 0.63163424], dtype=float32), {})

In [65]:
horizon = 2
num_particles = 5

sim_states = env.state

for h in range(horizon):
    print("h =", h, "\n")
    next_states = []
    for i in range(num_particles):
        print("i ", i, "\n")
        if h >0:
            env_i = copy.deepcopy(env)  # Assuming prob_vars.env is an environment object with a copy method
            env_i.reset(seed=seed)
            env_i.state = sim_states[i].numpy()  # Set the initial state of the environment
        else: # if h == 0:
            env_i = copy.deepcopy(env)  # Assuming prob_vars.env is an environment object with a copy method
            env_i.reset(seed=seed)
            if isinstance(sim_states, torch.Tensor):
                sim_states.detach().cpu().numpy()  # Safely convert to NumPy
            env_i.state = sim_states # Set the initial state of the environment
        print("env_i.state ", env_i.state, "\n")
        # print(env_i.step(env_i.action_space.sample()))
        action = env_i.action_space.sample()
        next_state_step, reward, terminated, truncated, info = env_i.step(env_i.action_space.sample())  # Sample a random action
        next_state = env_i.state
        print("action ", action, "\n")
        print("next_state ", next_state, "\n")
        next_states.append(next_state)
    
    # next_states = np.clip(next_states, env.observation_space.low, env.observation_space.high) # Clipping the next state is problematic since the step gives a 3D state and the env.state givees a 2D state
    sim_states = torch.tensor(next_states, dtype=torch.float32)
    print("sim_states", sim_states, "\n")
    # sim_states = torch.clip(sim_states, env.observation_space.low, env.observation_space.high)
    


h = 0 

i  0 

env_i.state  [1.2110423  0.63163422] 

action  [-1.0778373] 

next_state  [1.29267388 1.63263168] 

i  1 

env_i.state  [1.2110423  0.63163422] 

action  [-1.8573741] 

next_state  [1.26498214 1.07879693] 

i  2 

env_i.state  [1.2110423  0.63163422] 

action  [1.7408022] 

next_state  [1.2659763  1.09868002] 

i  3 

env_i.state  [1.2110423  0.63163422] 

action  [1.9067779] 

next_state  [1.28429773 1.46510871] 

i  4 

env_i.state  [1.2110423  0.63163422] 

action  [0.70322055] 

next_state  [1.27446341 1.26842231] 



ValueError: operands could not be broadcast together with shapes (5,2) (3,) (3,) 

## Lunar lander (continuous or discrete)

Doesn't work


In [67]:
env = gym.make('LunarLander-v3').unwrapped # .unwrapped is used to access the state directly
env.reset(seed=seed)


(array([ 8.8014605e-04,  1.4210069e+00,  8.9126542e-02,  4.4830140e-01,
        -1.0129989e-03, -2.0188505e-02,  0.0000000e+00,  0.0000000e+00],
       dtype=float32),
 {})

In [68]:
env.lander

b2Body(active=True,
       angle=-0.001012998865917325,
       angularDamping=0.0,
       angularVelocity=-0.05047126114368439,
       awake=True,
       bullet=False,
       contacts=[],
       fixedRotation=False,
       fixtures=[b2Fixture(body=b2Body(active=True,
                                      angle=-0.001012998865917325,
                                      angularDamping=0.0,
                                      angularVelocity=-0.05047126114368439,...  )],
       inertia=0.8333148956298828,
       joints=[b2JointEdge(joint=b2RevoluteJoint(active=True,
                                                anchorA=b2Vec2(10.0088,13.4067),
                                                anchorB=b2Vec2(10.0088,13.4067),...  )],
       linearDamping=0.0,
       linearVelocity=b2Vec2(0.445633,3.36226),
       localCenter=b2Vec2(0,0.101307),
       mass=4.816666603088379,
       massData=I=0.8333148956298828,center=b2Vec2(0,0.101307),mass=4.816666603088379,),
       position=b2Vec2(

In [ ]:
horizon = 2
num_particles = 5

sim_states = env.state

for h in range(horizon):
    print("h =", h, "\n")
    next_states = []
    for i in range(num_particles):
        print("i ", i, "\n")
        if h >0:
            env_i = copy.deepcopy(env)  # Assuming prob_vars.env is an environment object with a copy method
            env_i.reset(seed=seed)
            env_i.state = sim_states[i].numpy()  # Set the initial state of the environment
        else: # if h == 0:
            env_i = copy.deepcopy(env)  # Assuming prob_vars.env is an environment object with a copy method
            env_i.reset(seed=seed)
            if isinstance(sim_states, torch.Tensor):
                sim_states.detach().cpu().numpy()  # Safely convert to NumPy
            env_i.state = sim_states # Set the initial state of the environment
        print("env_i.state ", env_i.state, "\n")
        # print(env_i.step(env_i.action_space.sample()))
        action = env_i.action_space.sample()
        next_state_step, reward, terminated, truncated, info = env_i.step(action)  # Sample a random action
        next_state = env_i.state
        print("next_state ", next_state, "\n")
        next_states.append(next_state)
    
    next_states = np.clip(next_states, env.observation_space.low, env.observation_space.high)
    sim_states = torch.tensor(next_states, dtype=torch.float32)
    print("sim_states", sim_states, "\n")
    # sim_states = torch.clip(sim_states, env.observation_space.low, env.observation_space.high)
    


h = 0 

i  0 

env_i.state  [ 0.01927434  0.03158171 -0.01555932 -0.04551618] 

next_state  (0.019905971019187348, -0.08655294196659766, -0.016469647869333498, 0.1270900912606458) 

i  1 

env_i.state  [ 0.01927434  0.03158171 -0.01555932 -0.04551618] 

next_state  (0.019905971019187348, 0.0014594708235263036, -0.016469647869333498, -0.004912547883514723) 

i  2 

env_i.state  [ 0.01927434  0.03158171 -0.01555932 -0.04551618] 

next_state  (0.019905971019187348, -0.15515744052636463, -0.016469647869333498, 0.22998438287205802) 

i  3 

env_i.state  [ 0.01927434  0.03158171 -0.01555932 -0.04551618] 

next_state  (0.019905971019187348, -0.06759462778457094, -0.016469647869333498, 0.09865606216841635) 

i  4 

env_i.state  [ 0.01927434  0.03158171 -0.01555932 -0.04551618] 

next_state  (0.019905971019187348, -0.09673757295243982, -0.016469647869333498, 0.1423651885590966) 

sim_states tensor([[ 0.0199, -0.0866, -0.0165,  0.1271],
        [ 0.0199,  0.0015, -0.0165, -0.0049],
        [ 0.0

## Inverted Pendulum

Doesn't work


In [66]:
import gymnasium as gym
import numpy as np

env = gym.make('InvertedPendulum-v4')

# Reset environment (to initialize)
obs, info = env.reset()

# Define your custom state
custom_qpos = np.array([0.0, 0.1])   # cart position, pole angle
custom_qvel = np.array([0.0, 0.0])   # velocities

# Set the state
env.set_state = lambda qpos, qvel: (setattr(env.sim.data.qpos, "[:]", qpos), setattr(env.sim.data.qvel, "[:]", qvel))
env.set_state(custom_qpos, custom_qvel)

# Verify
print("New state qpos:", env.sim.data.qpos)
print("New state qvel:", env.sim.data.qvel)


c:\Users\nicle\anaconda3\Lib\site-packages\gymnasium\envs\registration.py:517: DeprecationWarning: WARN: The environment InvertedPendulum-v4 is out of date. You should consider upgrading to version `v5`.
  logger.deprecation(


AttributeError: 'TimeLimit' object has no attribute 'sim'

In [ ]:
env = gym.make("Pendulum", render_mode="rgb_array").unwrapped # .unwrapped is used to access the state directly
env.reset(seed=seed)


c:\Users\nicle\anaconda3\Lib\site-packages\gymnasium\envs\registration.py:525: UserWarning: WARN: Using the latest versioned environment `Pendulum-v1` instead of the unversioned environment `Pendulum`.
  logger.warn(


(array([0.35204402, 0.9359834 , 0.63163424], dtype=float32), {})

In [ ]:
horizon = 2
num_particles = 5

sim_states = env.state

for h in range(horizon):
    print("h =", h, "\n")
    next_states = []
    for i in range(num_particles):
        print("i ", i, "\n")
        if h >0:
            env_i = copy.deepcopy(env)  # Assuming prob_vars.env is an environment object with a copy method
            env_i.reset(seed=seed)
            env_i.state = sim_states[i].numpy()  # Set the initial state of the environment
        else: # if h == 0:
            env_i = copy.deepcopy(env)  # Assuming prob_vars.env is an environment object with a copy method
            env_i.reset(seed=seed)
            if isinstance(sim_states, torch.Tensor):
                sim_states.detach().cpu().numpy()  # Safely convert to NumPy
            env_i.state = sim_states # Set the initial state of the environment
        print("env_i.state ", env_i.state, "\n")
        # print(env_i.step(env_i.action_space.sample()))
        action = env_i.action_space.sample()
        next_state_step, reward, terminated, truncated, info = env_i.step(env_i.action_space.sample())  # Sample a random action
        next_state = env_i.state
        print("action ", action, "\n")
        print("next_state ", next_state, "\n")
        next_states.append(next_state)
    
    next_states = np.clip(next_states, env.observation_space.low, env.observation_space.high)
    sim_states = torch.tensor(next_states, dtype=torch.float32)
    print("sim_states", sim_states, "\n")
    # sim_states = torch.clip(sim_states, env.observation_space.low, env.observation_space.high)
    


h = 0 

i  0 

env_i.state  [1.2110423  0.63163422] 

action  [-1.0778373] 

next_state  [1.29267388 1.63263168] 

i  1 

env_i.state  [1.2110423  0.63163422] 

action  [-1.8573741] 

next_state  [1.26498214 1.07879693] 

i  2 

env_i.state  [1.2110423  0.63163422] 

action  [1.7408022] 

next_state  [1.2659763  1.09868002] 

i  3 

env_i.state  [1.2110423  0.63163422] 

action  [1.9067779] 

next_state  [1.28429773 1.46510871] 

i  4 

env_i.state  [1.2110423  0.63163422] 

action  [0.70322055] 

next_state  [1.27446341 1.26842231] 



ValueError: operands could not be broadcast together with shapes (5,2) (3,) (3,) 

## Same for MuJoCo Reacher and MuJoCo Pusher

